### ISSUE TITLE
Bug: ausloggen nach einem refresh

### ISSUE THREAD

**Issue by SebPasieka** [SebPasieka/NewsPaperApp#12]
- [x] Nach dem erfolgreichen Login soll der Nutzer auch nach einem refresh immer noch Zugang zu der Seite haben

**Comment by co0p** [comment]
please read about "storing data in the client" especially the "localStorage".

**Comment by SebPasieka** [comment]
![image](https://user-images.githubusercontent.com/56294721/118814964-048cf180-b8b1-11eb-8562-595ac81c4fb4.png)
