### ISSUE TITLE
Suche nach Artikeln [article preview]

### ISSUE THREAD

**Issue by SebPasieka** [SebPasieka/NewsPaperApp#4]
Als ein Nutzer möchte ich, dass mir passende Artikel angezeigt werden, wenn ich ein Schlagwort in die Suchleiste eingebe.

- [x] Nach Eingabe eines Suchbegriffes wird eine Übersicht von passenden Artikeln angezeigt.
- [x] Werden keine Artikel zu dem eingegebenen Suchbegriff gefunden wird dies gekennzeichnet.

**Comment by co0p** [comment]
"Nach Eingabe eines Suchbegriffes wird eine Übersicht von passenden Artikeln angezeigt." ist gutes Akzeptanzkriterium. 

"Es soll veranschaulicht werden, wenn keine Artikel zu dem Suchbegriff gefunden wurden." finde ich aktiv formuliert besser:
"Werden keine Artikel zu dem eingegebenen Suchbegriff gefunden wird dies gesondert gekennzeichnet"... oder so.

Das folgende AK kann ich nicht überprüfen ... "Die angezeigten Artikeln beinhalten oder haben mit dem Suchwort zu tun." Da kannst du dich auf api verlassen.
