### ISSUE TITLE
Artikel aufrufen können

### ISSUE THREAD

**Issue by SebPasieka** [SebPasieka/NewsPaperApp#5]
Als ein Nutzer möchte ich, ein Artikel angezeigt bekommen, wenn ich einen angeklickt habe, um ihn lesen zu können.
- [x] die Artikelvorschau soll angezeigt werden damit ein klicken auf ein Artikel möglich ist
- [x] durch einen Klick auf die Artikelvorschau öffnet sich die Detailansicht des Artikels

**Comment by co0p** [comment]
bitte in aktiver Sprache formulieren: 
Durch einen  Klick auf ein Artikelvorschau öffnet sich die Detailansicht des Artikels

**Comment by co0p** [comment]
bitte noch einen Test schreiben, der verifiziert, dass ein href attribut (also der link) zum Artikel existiert. Danach kannst du gern das ticket schließen!

achso... recherchier mal bitte das a element attribute "target". vielleicht willst du das verwenden.
