### ISSUE TITLE
Ausloggen 

### ISSUE THREAD

**Issue by SebPasieka** [SebPasieka/NewsPaperApp#7]
Als Entwickler möchte ich, dass sich Nutzer nach dem einloggen wieder ausloggen können. Nach dem manuellen ausloggen soll der Nutzer auf die Login-Seite weitergeleitet werden. 
- [x] durch einen Klick auf den "ausloggen"-Button soll der Nutzer ausgeloggt werden.
- [x] nach dem ausloggen soll der Nutzer auf die Login-Seite zurückgeworfen werden.
- [x] die Inhalte der Seite sollen nach dem ausloggen nicht mehr zugänglich sein.

**Comment by co0p** [comment]
ist das fertig? dann bitte ticket schließen
