### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by co0p** [SebPasieka/NewsPaperApp#8]
**As a dev** I want to **showcase my results** to the customer when ever I make changes to the master branch **in order to get feedback** in a timely manner. 

- [x] github actions triggers build on commit to master branch
- [x] deployment of build artifact to githubpages of this repo
- [x] build badge exists in the readme.md as well as a link to the githubpages page of the app
- [x] should only deloy when tests are passed

**Comment by SebPasieka** [comment]
Pipeline steps
- [ ] trigger tests on commit
- [ ] if the tests passed run build 
- [ ] deploy the build to github pages
